# Generated by Django 5.0.4 on 2024-05-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Статус'),
        ),
    ]
